// Captions
	
var internetCaption = function() {
	var captionHTML = "<p>";
	captionHTML += "<span class='current-caption' id='1' data-start='000000'>";
	captionHTML += "Now that we've looked at the architecture ";
	captionHTML += "of the internet, let's see how you might ";
	captionHTML += "</span>";
	captionHTML += "<span class='current-caption' id='2' data-start='000004'>";
	captionHTML += "connect your personal devices to ";
	captionHTML += "the internet inside your house. ";
	captionHTML += "</span>";
	captionHTML += "<span  class='current-caption' id='3' data-start='000007'>";
	captionHTML += "Well there are many ways to ";
	captionHTML += "connect to the internet, and ";
	captionHTML += "</span>";
	captionHTML += "<span  class='current-caption' id='4' data-start='000011'>";
	captionHTML += "most often people connect wirelessly. ";
	captionHTML += "</span>";
	captionHTML += "<span  class='current-caption' id='5' data-start='000013'>";
	captionHTML += "Let's look at an example of how ";
	captionHTML += "you can connect to the internet. ";
	captionHTML += "</span>";
	captionHTML += "<span  class='current-caption' id='6' data-start='000017'>";
	captionHTML += "If you live in a city or a town, ";
	captionHTML += "you probably have a coaxial cable for ";
	captionHTML += "</span>";
	captionHTML += "<span  class='current-caption' id='7' data-start='000022'>";
	captionHTML += "cable Internet, or a phone line if you ";
	captionHTML += "have DSL, running to the outside of ";
	captionHTML += "</span>";
	captionHTML += "<span  class='current-caption' id='8' data-start='000026'>";
	captionHTML += "your house, that connects you to ";
	captionHTML += "the Internet Service Provider, or ISP. ";
	captionHTML += "</span>";
	captionHTML += "<span  class='current-caption' id='9' data-start='000032'>";
	captionHTML += "If you live far out in the country, ";
	captionHTML += "you'll more likely have ";
	captionHTML += "</span>";
	captionHTML += "<span  class='current-caption' id='10' data-start='000034'>";
	captionHTML += "a dish outside your house, connecting ";
	captionHTML += "you wirelessly to your closest ISP, or ";
	captionHTML += "</span>";
	captionHTML += "<span  class='current-caption' id='11' data-start='000039'>";
	captionHTML += "you might also use the telephone system. ";
	captionHTML += "</span>";
	captionHTML += "<span  class='current-caption' id='12' data-start='000042'>";
	captionHTML += "Whether a wire comes straight from ";
	captionHTML += "the ISP hookup outside your house, or ";
	captionHTML += "</span>";
	captionHTML += "<span  class='current-caption' id='13' data-start='000046'>";
	captionHTML += "it travels over radio  ";
	captionHTML += "waves from your roof, ";
	captionHTML += "</span>";
	captionHTML += "<span  class='current-caption' id='14' data-start='000049'>";
	captionHTML +=  "the first stop a wire will make once ";
	captionHTML +=  "inside your house, is at your modem. ";
	captionHTML +=  "</span>";
	captionHTML +=  "<span  class='current-caption' id='15' data-start='000053'>";
	captionHTML +=  "A modem is what connects the internet ";
	captionHTML +=  "to your network at home. ";
	captionHTML +=  "</span>";
	captionHTML +=  "<span  class='current-caption' id='16' data-start='000057'>";
	captionHTML +=  "A few common residential modems are DSL or...";
	captionHTML +=  "</span>";
	captionHTML +=  "<span data-start='000100'></span>" // Workaround: In order to highlight last line;
	captionHTML +=  "</p>";
	return captionHTML;
}

